"""add parse_version to reports and biomarker_values

Revision ID: b7ad79000c92
Revises: c56eb8715c20
Create Date: 2026-06-28 10:53:41.704660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ad79000c92'
down_revision: Union[str, None] = 'c56eb8715c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarker_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_version', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_version', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('parse_version')

    with op.batch_alter_table('biomarker_values', schema=None) as batch_op:
        batch_op.drop_column('parse_version')

    # ### end Alembic commands ###
